packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  pg: ^8.16.3
  pg-query-stream: ^4.10.3
  reflect-metadata: ^0.2.2
  typeorm: ^0.3.26
  '@types/node': ^20.19.14
  dayjs: ^1.11.18
  bullmq: ^5.58.5
  ioredis: ^5.7.0
  dotenv: ^17.2.2
